
    
    


datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  production:
    username: ${{Postgres.PGUSER}}
    password: ${{Postgres.PGPASSWORD}}
    url: ${{Postgres.DATABASE_URL}}

ebean:
  ddl:
    run: true
    generate: true
#  migration:
#    run: true