
    
    


datasource:
  db:
#  default: ${APP_ENV}
#  development:
#    username: ""
#    password: ""
#    url: "jdbc:h2:./database"
#  production:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: jdbc:${DATABASE_URL}

ebean:
  ddl:
    run: true
    generate: true
#  migration:
#    run: true