ebean:
#  ddl:
#    run: true
#    generate: true
  migration:
    run: true

datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

