
    
    


datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  production:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: ${DATABASE_URL}

ebean:
  ddl:
    run: true
    generate: true
#  migration:
#    run: true