-- apply changes
create table url (
  id                            bigint generated by default as identity not null,
  create_at                     timestamptz not null,
  name                          text,
  constraint pk_url primary key (id)
);

